/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FreeCoinsResult = IDL.Variant({
  'ok' : IDL.Nat,
  'err' : IDL.Variant({ 'cooldownActive' : IDL.Null }),
});
export const PlayerReferral = IDL.Record({
  'username' : IDL.Text,
  'referredBy' : IDL.Text,
});
export const RoundLogEntry = IDL.Record({
  'question' : IDL.Text,
  'winner' : IDL.Opt(IDL.Text),
  'totalSubmissions' : IDL.Nat,
  'timeTaken' : IDL.Opt(IDL.Int),
  'roundNumber' : IDL.Nat,
});
export const AdminExtras = IDL.Record({
  'kickedPlayers' : IDL.Vec(IDL.Text),
  'activePlayers' : IDL.Nat,
  'playerReferrals' : IDL.Vec(PlayerReferral),
  'blockedPlayers' : IDL.Vec(IDL.Text),
  'suspiciousUsers' : IDL.Vec(IDL.Text),
  'roomCode' : IDL.Text,
  'roundLog' : IDL.Vec(RoundLogEntry),
});
export const QuizStatus = IDL.Variant({
  'live' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
});
export const AnswerMode = IDL.Variant({
  'strict' : IDL.Null,
  'smart' : IDL.Null,
});
export const AnswerStatus = IDL.Variant({
  'almost' : IDL.Null,
  'correct' : IDL.Null,
  'wrong' : IDL.Null,
});
export const Submission = IDL.Record({
  'answerStatus' : AnswerStatus,
  'username' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const QuizStateAdmin = IDL.Record({
  'startTime' : IDL.Int,
  'status' : QuizStatus,
  'question' : IDL.Text,
  'mode' : AnswerMode,
  'winner' : IDL.Opt(IDL.Text),
  'timerSeconds' : IDL.Nat,
  'submissions' : IDL.Vec(Submission),
  'totalActivePlayers' : IDL.Nat,
  'correctAnswers' : IDL.Vec(IDL.Text),
  'suspiciousUsers' : IDL.Vec(IDL.Text),
});
export const AutoModeSettings = IDL.Record({
  'rewardAmount' : IDL.Nat,
  'timerSeconds' : IDL.Nat,
  'enabled' : IDL.Bool,
});
export const CoinSettings = IDL.Record({
  'entryFee' : IDL.Nat,
  'winBonus' : IDL.Nat,
});
export const QuizStatePublic = IDL.Record({
  'startTime' : IDL.Int,
  'status' : QuizStatus,
  'question' : IDL.Text,
  'winner' : IDL.Opt(IDL.Text),
  'timerSeconds' : IDL.Nat,
  'submissions' : IDL.Vec(Submission),
});
export const ReferralCount = IDL.Record({
  'inviter' : IDL.Text,
  'count' : IDL.Nat,
});
export const ScoreboardEntry = IDL.Record({
  'streak' : IDL.Nat,
  'username' : IDL.Text,
  'wins' : IDL.Nat,
});
export const WinEntry = IDL.Record({
  'username' : IDL.Text,
  'timeTaken' : IDL.Int,
});
export const ScoreboardData = IDL.Record({
  'scoreboard' : IDL.Vec(ScoreboardEntry),
  'winHistory' : IDL.Vec(WinEntry),
});
export const PlayerWallet = IDL.Record({
  'totalEarned' : IDL.Nat,
  'totalWithdrawn' : IDL.Nat,
  'pendingBalance' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'username' : IDL.Text,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const JoinError = IDL.Variant({
  'nameTaken' : IDL.Null,
  'playerKicked' : IDL.Null,
  'invalidName' : IDL.Null,
  'playerBlocked' : IDL.Null,
  'wrongRoomCode' : IDL.Null,
});
export const WithdrawalError = IDL.Variant({
  'insufficientBalance' : IDL.Null,
  'invalidUpiId' : IDL.Null,
  'pendingRequestExists' : IDL.Null,
  'cooldownActive' : IDL.Null,
});
export const QuizError = IDL.Variant({
  'answerNotAccepted' : IDL.Text,
  'quizAlreadyHasWinner' : IDL.Null,
  'quizNotLive' : IDL.Null,
  'insufficientCoins' : IDL.Null,
  'answerLimitExceeded' : IDL.Null,
});
export const AutoRoundResult = IDL.Record({
  'state' : QuizStatePublic,
  'questionId' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'blockPlayer' : IDL.Func([IDL.Text], [], []),
  'claimFreeCoins' : IDL.Func([IDL.Text], [FreeCoinsResult], []),
  'endRound' : IDL.Func([], [], []),
  'generateRoomCode' : IDL.Func([], [IDL.Text], []),
  'getAdminExtras' : IDL.Func([], [AdminExtras], ['query']),
  'getAdminState' : IDL.Func([], [QuizStateAdmin], ['query']),
  'getAutoModeSettings' : IDL.Func([], [AutoModeSettings], ['query']),
  'getCoinBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getCoinSettings' : IDL.Func([], [CoinSettings], ['query']),
  'getInviterForPlayer' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getMinWithdrawal' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuizState' : IDL.Func([], [QuizStatePublic], ['query']),
  'getReferralCounts' : IDL.Func([], [IDL.Vec(ReferralCount)], ['query']),
  'getRoundLog' : IDL.Func([], [IDL.Vec(RoundLogEntry)], ['query']),
  'getScoreboard' : IDL.Func([], [ScoreboardData], ['query']),
  'getWallet' : IDL.Func([IDL.Text], [PlayerWallet], ['query']),
  'getWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'joinSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : JoinError })],
      [],
    ),
  'kickPlayer' : IDL.Func([IDL.Text], [], []),
  'markWithdrawalPaid' : IDL.Func([IDL.Nat], [], []),
  'requestWithdrawal' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : WithdrawalError })],
      [],
    ),
  'resetAll' : IDL.Func([], [], []),
  'resetQuiz' : IDL.Func([], [], []),
  'setAutoMode' : IDL.Func([IDL.Bool, IDL.Nat, IDL.Nat], [], []),
  'setCoinEntryFee' : IDL.Func([IDL.Nat], [], []),
  'setCoinWinBonus' : IDL.Func([IDL.Nat], [], []),
  'setMinWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'startNewRound' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, AnswerMode, IDL.Nat],
      [IDL.Variant({ 'ok' : QuizStatePublic })],
      [],
    ),
  'startQuiz' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, AnswerMode, IDL.Nat],
      [IDL.Variant({ 'ok' : QuizStatePublic })],
      [],
    ),
  'submitAnswer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : QuizStatePublic, 'err' : QuizError })],
      [],
    ),
  'triggerAutoRound' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : AutoRoundResult, 'err' : IDL.Text })],
      [],
    ),
  'unblockPlayer' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FreeCoinsResult = IDL.Variant({
    'ok' : IDL.Nat,
    'err' : IDL.Variant({ 'cooldownActive' : IDL.Null }),
  });
  const PlayerReferral = IDL.Record({
    'username' : IDL.Text,
    'referredBy' : IDL.Text,
  });
  const RoundLogEntry = IDL.Record({
    'question' : IDL.Text,
    'winner' : IDL.Opt(IDL.Text),
    'totalSubmissions' : IDL.Nat,
    'timeTaken' : IDL.Opt(IDL.Int),
    'roundNumber' : IDL.Nat,
  });
  const AdminExtras = IDL.Record({
    'kickedPlayers' : IDL.Vec(IDL.Text),
    'activePlayers' : IDL.Nat,
    'playerReferrals' : IDL.Vec(PlayerReferral),
    'blockedPlayers' : IDL.Vec(IDL.Text),
    'suspiciousUsers' : IDL.Vec(IDL.Text),
    'roomCode' : IDL.Text,
    'roundLog' : IDL.Vec(RoundLogEntry),
  });
  const QuizStatus = IDL.Variant({
    'live' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const AnswerMode = IDL.Variant({ 'strict' : IDL.Null, 'smart' : IDL.Null });
  const AnswerStatus = IDL.Variant({
    'almost' : IDL.Null,
    'correct' : IDL.Null,
    'wrong' : IDL.Null,
  });
  const Submission = IDL.Record({
    'answerStatus' : AnswerStatus,
    'username' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const QuizStateAdmin = IDL.Record({
    'startTime' : IDL.Int,
    'status' : QuizStatus,
    'question' : IDL.Text,
    'mode' : AnswerMode,
    'winner' : IDL.Opt(IDL.Text),
    'timerSeconds' : IDL.Nat,
    'submissions' : IDL.Vec(Submission),
    'totalActivePlayers' : IDL.Nat,
    'correctAnswers' : IDL.Vec(IDL.Text),
    'suspiciousUsers' : IDL.Vec(IDL.Text),
  });
  const AutoModeSettings = IDL.Record({
    'rewardAmount' : IDL.Nat,
    'timerSeconds' : IDL.Nat,
    'enabled' : IDL.Bool,
  });
  const CoinSettings = IDL.Record({
    'entryFee' : IDL.Nat,
    'winBonus' : IDL.Nat,
  });
  const QuizStatePublic = IDL.Record({
    'startTime' : IDL.Int,
    'status' : QuizStatus,
    'question' : IDL.Text,
    'winner' : IDL.Opt(IDL.Text),
    'timerSeconds' : IDL.Nat,
    'submissions' : IDL.Vec(Submission),
  });
  const ReferralCount = IDL.Record({ 'inviter' : IDL.Text, 'count' : IDL.Nat });
  const ScoreboardEntry = IDL.Record({
    'streak' : IDL.Nat,
    'username' : IDL.Text,
    'wins' : IDL.Nat,
  });
  const WinEntry = IDL.Record({ 'username' : IDL.Text, 'timeTaken' : IDL.Int });
  const ScoreboardData = IDL.Record({
    'scoreboard' : IDL.Vec(ScoreboardEntry),
    'winHistory' : IDL.Vec(WinEntry),
  });
  const PlayerWallet = IDL.Record({
    'totalEarned' : IDL.Nat,
    'totalWithdrawn' : IDL.Nat,
    'pendingBalance' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'username' : IDL.Text,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const JoinError = IDL.Variant({
    'nameTaken' : IDL.Null,
    'playerKicked' : IDL.Null,
    'invalidName' : IDL.Null,
    'playerBlocked' : IDL.Null,
    'wrongRoomCode' : IDL.Null,
  });
  const WithdrawalError = IDL.Variant({
    'insufficientBalance' : IDL.Null,
    'invalidUpiId' : IDL.Null,
    'pendingRequestExists' : IDL.Null,
    'cooldownActive' : IDL.Null,
  });
  const QuizError = IDL.Variant({
    'answerNotAccepted' : IDL.Text,
    'quizAlreadyHasWinner' : IDL.Null,
    'quizNotLive' : IDL.Null,
    'insufficientCoins' : IDL.Null,
    'answerLimitExceeded' : IDL.Null,
  });
  const AutoRoundResult = IDL.Record({
    'state' : QuizStatePublic,
    'questionId' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'blockPlayer' : IDL.Func([IDL.Text], [], []),
    'claimFreeCoins' : IDL.Func([IDL.Text], [FreeCoinsResult], []),
    'endRound' : IDL.Func([], [], []),
    'generateRoomCode' : IDL.Func([], [IDL.Text], []),
    'getAdminExtras' : IDL.Func([], [AdminExtras], ['query']),
    'getAdminState' : IDL.Func([], [QuizStateAdmin], ['query']),
    'getAutoModeSettings' : IDL.Func([], [AutoModeSettings], ['query']),
    'getCoinBalance' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getCoinSettings' : IDL.Func([], [CoinSettings], ['query']),
    'getInviterForPlayer' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getMinWithdrawal' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuizState' : IDL.Func([], [QuizStatePublic], ['query']),
    'getReferralCounts' : IDL.Func([], [IDL.Vec(ReferralCount)], ['query']),
    'getRoundLog' : IDL.Func([], [IDL.Vec(RoundLogEntry)], ['query']),
    'getScoreboard' : IDL.Func([], [ScoreboardData], ['query']),
    'getWallet' : IDL.Func([IDL.Text], [PlayerWallet], ['query']),
    'getWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'joinSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : JoinError })],
        [],
      ),
    'kickPlayer' : IDL.Func([IDL.Text], [], []),
    'markWithdrawalPaid' : IDL.Func([IDL.Nat], [], []),
    'requestWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : WithdrawalError })],
        [],
      ),
    'resetAll' : IDL.Func([], [], []),
    'resetQuiz' : IDL.Func([], [], []),
    'setAutoMode' : IDL.Func([IDL.Bool, IDL.Nat, IDL.Nat], [], []),
    'setCoinEntryFee' : IDL.Func([IDL.Nat], [], []),
    'setCoinWinBonus' : IDL.Func([IDL.Nat], [], []),
    'setMinWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'startNewRound' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, AnswerMode, IDL.Nat],
        [IDL.Variant({ 'ok' : QuizStatePublic })],
        [],
      ),
    'startQuiz' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, AnswerMode, IDL.Nat],
        [IDL.Variant({ 'ok' : QuizStatePublic })],
        [],
      ),
    'submitAnswer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : QuizStatePublic, 'err' : QuizError })],
        [],
      ),
    'triggerAutoRound' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : AutoRoundResult, 'err' : IDL.Text })],
        [],
      ),
    'unblockPlayer' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };