/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminExtras {
  'kickedPlayers' : Array<string>,
  'activePlayers' : bigint,
  'playerReferrals' : Array<PlayerReferral>,
  'blockedPlayers' : Array<string>,
  'suspiciousUsers' : Array<string>,
  'roomCode' : string,
  'roundLog' : Array<RoundLogEntry>,
}
export type AnswerMode = { 'strict' : null } |
  { 'smart' : null };
export type AnswerStatus = { 'almost' : null } |
  { 'correct' : null } |
  { 'wrong' : null };
export interface AutoModeSettings {
  'rewardAmount' : bigint,
  'timerSeconds' : bigint,
  'enabled' : boolean,
}
export interface AutoRoundResult {
  'state' : QuizStatePublic,
  'questionId' : bigint,
  'category' : string,
}
export interface CoinSettings { 'entryFee' : bigint, 'winBonus' : bigint }
export type FreeCoinsResult = { 'ok' : bigint } |
  { 'err' : { 'cooldownActive' : null } };
export type JoinError = { 'nameTaken' : null } |
  { 'playerKicked' : null } |
  { 'invalidName' : null } |
  { 'playerBlocked' : null } |
  { 'wrongRoomCode' : null };
export interface PlayerReferral { 'username' : string, 'referredBy' : string }
export interface PlayerWallet {
  'totalEarned' : bigint,
  'totalWithdrawn' : bigint,
  'pendingBalance' : bigint,
}
export type QuizError = { 'answerNotAccepted' : string } |
  { 'quizAlreadyHasWinner' : null } |
  { 'quizNotLive' : null } |
  { 'insufficientCoins' : null } |
  { 'answerLimitExceeded' : null };
export interface QuizStateAdmin {
  'startTime' : bigint,
  'status' : QuizStatus,
  'question' : string,
  'mode' : AnswerMode,
  'winner' : [] | [string],
  'timerSeconds' : bigint,
  'submissions' : Array<Submission>,
  'totalActivePlayers' : bigint,
  'correctAnswers' : Array<string>,
  'suspiciousUsers' : Array<string>,
}
export interface QuizStatePublic {
  'startTime' : bigint,
  'status' : QuizStatus,
  'question' : string,
  'winner' : [] | [string],
  'timerSeconds' : bigint,
  'submissions' : Array<Submission>,
}
export type QuizStatus = { 'live' : null } |
  { 'finished' : null } |
  { 'waiting' : null };
export interface ReferralCount { 'inviter' : string, 'count' : bigint }
export interface RoundLogEntry {
  'question' : string,
  'winner' : [] | [string],
  'totalSubmissions' : bigint,
  'timeTaken' : [] | [bigint],
  'roundNumber' : bigint,
}
export interface ScoreboardData {
  'scoreboard' : Array<ScoreboardEntry>,
  'winHistory' : Array<WinEntry>,
}
export interface ScoreboardEntry {
  'streak' : bigint,
  'username' : string,
  'wins' : bigint,
}
export interface Submission {
  'answerStatus' : AnswerStatus,
  'username' : string,
  'answer' : string,
  'timestamp' : bigint,
}
export interface WinEntry { 'username' : string, 'timeTaken' : bigint }
export type WithdrawalError = { 'insufficientBalance' : null } |
  { 'invalidUpiId' : null } |
  { 'pendingRequestExists' : null } |
  { 'cooldownActive' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'username' : string,
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'paid' : null };
export interface _SERVICE {
  'blockPlayer' : ActorMethod<[string], undefined>,
  'claimFreeCoins' : ActorMethod<[string], FreeCoinsResult>,
  'endRound' : ActorMethod<[], undefined>,
  'generateRoomCode' : ActorMethod<[], string>,
  'getAdminExtras' : ActorMethod<[], AdminExtras>,
  'getAdminState' : ActorMethod<[], QuizStateAdmin>,
  'getAutoModeSettings' : ActorMethod<[], AutoModeSettings>,
  'getCoinBalance' : ActorMethod<[string], bigint>,
  'getCoinSettings' : ActorMethod<[], CoinSettings>,
  'getInviterForPlayer' : ActorMethod<[string], string>,
  'getMinWithdrawal' : ActorMethod<[], bigint>,
  'getQuizState' : ActorMethod<[], QuizStatePublic>,
  'getReferralCounts' : ActorMethod<[], Array<ReferralCount>>,
  'getRoundLog' : ActorMethod<[], Array<RoundLogEntry>>,
  'getScoreboard' : ActorMethod<[], ScoreboardData>,
  'getWallet' : ActorMethod<[string], PlayerWallet>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'joinSession' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : JoinError }
  >,
  'kickPlayer' : ActorMethod<[string], undefined>,
  'markWithdrawalPaid' : ActorMethod<[bigint], undefined>,
  'requestWithdrawal' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : WithdrawalError }
  >,
  'resetAll' : ActorMethod<[], undefined>,
  'resetQuiz' : ActorMethod<[], undefined>,
  'setAutoMode' : ActorMethod<[boolean, bigint, bigint], undefined>,
  'setCoinEntryFee' : ActorMethod<[bigint], undefined>,
  'setCoinWinBonus' : ActorMethod<[bigint], undefined>,
  'setMinWithdrawal' : ActorMethod<[bigint], undefined>,
  'startNewRound' : ActorMethod<
    [string, string, bigint, AnswerMode, bigint],
    { 'ok' : QuizStatePublic }
  >,
  'startQuiz' : ActorMethod<
    [string, string, bigint, AnswerMode, bigint],
    { 'ok' : QuizStatePublic }
  >,
  'submitAnswer' : ActorMethod<
    [string, string],
    { 'ok' : QuizStatePublic } |
      { 'err' : QuizError }
  >,
  'triggerAutoRound' : ActorMethod<
    [],
    { 'ok' : AutoRoundResult } |
      { 'err' : string }
  >,
  'unblockPlayer' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];