/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScoreboardEntry {
    streak: bigint;
    username: string;
    wins: bigint;
}
export interface AutoRoundResult {
    state: QuizStatePublic;
    questionId: bigint;
    category: string;
}
export interface AutoModeSettings {
    rewardAmount: bigint;
    timerSeconds: bigint;
    enabled: boolean;
}
export interface RoundLogEntry {
    question: string;
    winner?: string;
    totalSubmissions: bigint;
    timeTaken?: bigint;
    roundNumber: bigint;
}
export interface ScoreboardData {
    scoreboard: Array<ScoreboardEntry>;
    winHistory: Array<WinEntry>;
}
export interface CoinSettings {
    entryFee: bigint;
    winBonus: bigint;
}
export interface QuizStateAdmin {
    startTime: bigint;
    status: QuizStatus;
    question: string;
    mode: AnswerMode;
    winner?: string;
    timerSeconds: bigint;
    submissions: Array<Submission>;
    totalActivePlayers: bigint;
    correctAnswers: Array<string>;
    suspiciousUsers: Array<string>;
}
export interface AdminExtras {
    kickedPlayers: Array<string>;
    activePlayers: bigint;
    playerReferrals: Array<PlayerReferral>;
    blockedPlayers: Array<string>;
    suspiciousUsers: Array<string>;
    roomCode: string;
    roundLog: Array<RoundLogEntry>;
}
export type QuizError = {
    __kind__: "answerNotAccepted";
    answerNotAccepted: string;
} | {
    __kind__: "quizAlreadyHasWinner";
    quizAlreadyHasWinner: null;
} | {
    __kind__: "quizNotLive";
    quizNotLive: null;
} | {
    __kind__: "insufficientCoins";
    insufficientCoins: null;
} | {
    __kind__: "answerLimitExceeded";
    answerLimitExceeded: null;
};
export interface ReferralCount {
    inviter: string;
    count: bigint;
}
export interface WinEntry {
    username: string;
    timeTaken: bigint;
}
export interface PlayerWallet {
    totalEarned: bigint;
    totalWithdrawn: bigint;
    pendingBalance: bigint;
}
export interface PlayerReferral {
    username: string;
    referredBy: string;
}
export type FreeCoinsResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Variant_cooldownActive;
};
export interface QuizStatePublic {
    startTime: bigint;
    status: QuizStatus;
    question: string;
    winner?: string;
    timerSeconds: bigint;
    submissions: Array<Submission>;
}
export interface WithdrawalRequest {
    id: bigint;
    status: WithdrawalStatus;
    username: string;
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
}
export interface Submission {
    answerStatus: AnswerStatus;
    username: string;
    answer: string;
    timestamp: bigint;
}
export enum AnswerMode {
    strict = "strict",
    smart = "smart"
}
export enum AnswerStatus {
    almost = "almost",
    correct = "correct",
    wrong = "wrong"
}
export enum JoinError {
    nameTaken = "nameTaken",
    playerKicked = "playerKicked",
    invalidName = "invalidName",
    playerBlocked = "playerBlocked",
    wrongRoomCode = "wrongRoomCode"
}
export enum QuizStatus {
    live = "live",
    finished = "finished",
    waiting = "waiting"
}
export enum Variant_cooldownActive {
    cooldownActive = "cooldownActive"
}
export enum WithdrawalError {
    insufficientBalance = "insufficientBalance",
    invalidUpiId = "invalidUpiId",
    pendingRequestExists = "pendingRequestExists",
    cooldownActive = "cooldownActive"
}
export enum WithdrawalStatus {
    pending = "pending",
    paid = "paid"
}
export interface backendInterface {
    blockPlayer(username: string): Promise<void>;
    claimFreeCoins(username: string): Promise<FreeCoinsResult>;
    endRound(): Promise<void>;
    generateRoomCode(): Promise<string>;
    getAdminExtras(): Promise<AdminExtras>;
    getAdminState(): Promise<QuizStateAdmin>;
    getAutoModeSettings(): Promise<AutoModeSettings>;
    getCoinBalance(username: string): Promise<bigint>;
    getCoinSettings(): Promise<CoinSettings>;
    getInviterForPlayer(username: string): Promise<string>;
    getMinWithdrawal(): Promise<bigint>;
    getQuizState(): Promise<QuizStatePublic>;
    getReferralCounts(): Promise<Array<ReferralCount>>;
    getRoundLog(): Promise<Array<RoundLogEntry>>;
    getScoreboard(): Promise<ScoreboardData>;
    getWallet(username: string): Promise<PlayerWallet>;
    getWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    joinSession(username: string, code: string, referredBy: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: JoinError;
    }>;
    kickPlayer(username: string): Promise<void>;
    markWithdrawalPaid(requestId: bigint): Promise<void>;
    requestWithdrawal(username: string, upiId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WithdrawalError;
    }>;
    resetAll(): Promise<void>;
    resetQuiz(): Promise<void>;
    setAutoMode(enabled: boolean, rewardAmount: bigint, timerSeconds: bigint): Promise<void>;
    setCoinEntryFee(fee: bigint): Promise<void>;
    setCoinWinBonus(bonus: bigint): Promise<void>;
    setMinWithdrawal(amount: bigint): Promise<void>;
    startNewRound(question: string, correctAnswers: string, timerSeconds: bigint, mode: AnswerMode, rewardAmount: bigint): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    }>;
    startQuiz(question: string, correctAnswers: string, timerSeconds: bigint, mode: AnswerMode, rewardAmount: bigint): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    }>;
    submitAnswer(username: string, answer: string): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    } | {
        __kind__: "err";
        err: QuizError;
    }>;
    triggerAutoRound(): Promise<{
        __kind__: "ok";
        ok: AutoRoundResult;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unblockPlayer(username: string): Promise<void>;
}
import type { AdminExtras as _AdminExtras, AnswerMode as _AnswerMode, AnswerStatus as _AnswerStatus, AutoRoundResult as _AutoRoundResult, FreeCoinsResult as _FreeCoinsResult, JoinError as _JoinError, PlayerReferral as _PlayerReferral, QuizError as _QuizError, QuizStateAdmin as _QuizStateAdmin, QuizStatePublic as _QuizStatePublic, QuizStatus as _QuizStatus, RoundLogEntry as _RoundLogEntry, Submission as _Submission, WithdrawalError as _WithdrawalError, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async blockPlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockPlayer(arg0);
            return result;
        }
    }
    async claimFreeCoins(arg0: string): Promise<FreeCoinsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFreeCoins(arg0);
                return from_candid_FreeCoinsResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFreeCoins(arg0);
            return from_candid_FreeCoinsResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async endRound(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endRound();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endRound();
            return result;
        }
    }
    async generateRoomCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRoomCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRoomCode();
            return result;
        }
    }
    async getAdminExtras(): Promise<AdminExtras> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminExtras();
                return from_candid_AdminExtras_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminExtras();
            return from_candid_AdminExtras_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminState(): Promise<QuizStateAdmin> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminState();
                return from_candid_QuizStateAdmin_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminState();
            return from_candid_QuizStateAdmin_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAutoModeSettings(): Promise<AutoModeSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getAutoModeSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAutoModeSettings();
            return result;
        }
    }
    async getCoinBalance(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance(arg0);
            return result;
        }
    }
    async getCoinSettings(): Promise<CoinSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinSettings();
            return result;
        }
    }
    async getInviterForPlayer(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviterForPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviterForPlayer(arg0);
            return result;
        }
    }
    async getMinWithdrawal(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMinWithdrawal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMinWithdrawal();
            return result;
        }
    }
    async getQuizState(): Promise<QuizStatePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizState();
                return from_candid_QuizStatePublic_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizState();
            return from_candid_QuizStatePublic_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralCounts(): Promise<Array<ReferralCount>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCounts();
            return result;
        }
    }
    async getRoundLog(): Promise<Array<RoundLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoundLog();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoundLog();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScoreboard(): Promise<ScoreboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getScoreboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScoreboard();
            return result;
        }
    }
    async getWallet(arg0: string): Promise<PlayerWallet> {
        if (this.processError) {
            try {
                const result = await this.actor.getWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWallet(arg0);
            return result;
        }
    }
    async getWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequests();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequests();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinSession(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: JoinError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0, arg1, arg2);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0, arg1, arg2);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async kickPlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.kickPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kickPlayer(arg0);
            return result;
        }
    }
    async markWithdrawalPaid(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWithdrawalPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWithdrawalPaid(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: WithdrawalError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1);
                return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1);
            return from_candid_variant_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetAll(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAll();
            return result;
        }
    }
    async resetQuiz(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetQuiz();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetQuiz();
            return result;
        }
    }
    async setAutoMode(arg0: boolean, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAutoMode(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAutoMode(arg0, arg1, arg2);
            return result;
        }
    }
    async setCoinEntryFee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoinEntryFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoinEntryFee(arg0);
            return result;
        }
    }
    async setCoinWinBonus(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoinWinBonus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoinWinBonus(arg0);
            return result;
        }
    }
    async setMinWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMinWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMinWithdrawal(arg0);
            return result;
        }
    }
    async startNewRound(arg0: string, arg1: string, arg2: bigint, arg3: AnswerMode, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startNewRound(arg0, arg1, arg2, to_candid_AnswerMode_n35(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startNewRound(arg0, arg1, arg2, to_candid_AnswerMode_n35(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async startQuiz(arg0: string, arg1: string, arg2: bigint, arg3: AnswerMode, arg4: bigint): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startQuiz(arg0, arg1, arg2, to_candid_AnswerMode_n35(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startQuiz(arg0, arg1, arg2, to_candid_AnswerMode_n35(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAnswer(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: QuizStatePublic;
    } | {
        __kind__: "err";
        err: QuizError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAnswer(arg0, arg1);
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAnswer(arg0, arg1);
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async triggerAutoRound(): Promise<{
        __kind__: "ok";
        ok: AutoRoundResult;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerAutoRound();
                return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerAutoRound();
            return from_candid_variant_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async unblockPlayer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockPlayer(arg0);
            return result;
        }
    }
}
function from_candid_AdminExtras_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminExtras): AdminExtras {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AnswerMode_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerMode): AnswerMode {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AnswerStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnswerStatus): AnswerStatus {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_AutoRoundResult_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AutoRoundResult): AutoRoundResult {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_FreeCoinsResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FreeCoinsResult): FreeCoinsResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_JoinError_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JoinError): JoinError {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_QuizError_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizError): QuizError {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_QuizStateAdmin_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizStateAdmin): QuizStateAdmin {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuizStatePublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizStatePublic): QuizStatePublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_QuizStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuizStatus): QuizStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RoundLogEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoundLogEntry): RoundLogEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalError_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalError): WithdrawalError {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: _QuizStatus;
    question: string;
    mode: _AnswerMode;
    winner: [] | [string];
    timerSeconds: bigint;
    submissions: Array<_Submission>;
    totalActivePlayers: bigint;
    correctAnswers: Array<string>;
    suspiciousUsers: Array<string>;
}): {
    startTime: bigint;
    status: QuizStatus;
    question: string;
    mode: AnswerMode;
    winner?: string;
    timerSeconds: bigint;
    submissions: Array<Submission>;
    totalActivePlayers: bigint;
    correctAnswers: Array<string>;
    suspiciousUsers: Array<string>;
} {
    return {
        startTime: value.startTime,
        status: from_candid_QuizStatus_n13(_uploadFile, _downloadFile, value.status),
        question: value.question,
        mode: from_candid_AnswerMode_n15(_uploadFile, _downloadFile, value.mode),
        winner: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.winner)),
        timerSeconds: value.timerSeconds,
        submissions: from_candid_vec_n17(_uploadFile, _downloadFile, value.submissions),
        totalActivePlayers: value.totalActivePlayers,
        correctAnswers: value.correctAnswers,
        suspiciousUsers: value.suspiciousUsers
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answerStatus: _AnswerStatus;
    username: string;
    answer: string;
    timestamp: bigint;
}): {
    answerStatus: AnswerStatus;
    username: string;
    answer: string;
    timestamp: bigint;
} {
    return {
        answerStatus: from_candid_AnswerStatus_n20(_uploadFile, _downloadFile, value.answerStatus),
        username: value.username,
        answer: value.answer,
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: _QuizStatus;
    question: string;
    winner: [] | [string];
    timerSeconds: bigint;
    submissions: Array<_Submission>;
}): {
    startTime: bigint;
    status: QuizStatus;
    question: string;
    winner?: string;
    timerSeconds: bigint;
    submissions: Array<Submission>;
} {
    return {
        startTime: value.startTime,
        status: from_candid_QuizStatus_n13(_uploadFile, _downloadFile, value.status),
        question: value.question,
        winner: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.winner)),
        timerSeconds: value.timerSeconds,
        submissions: from_candid_vec_n17(_uploadFile, _downloadFile, value.submissions)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawalStatus;
    username: string;
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
}): {
    id: bigint;
    status: WithdrawalStatus;
    username: string;
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n27(_uploadFile, _downloadFile, value.status),
        username: value.username,
        upiId: value.upiId,
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    state: _QuizStatePublic;
    questionId: bigint;
    category: string;
}): {
    state: QuizStatePublic;
    questionId: bigint;
    category: string;
} {
    return {
        state: from_candid_QuizStatePublic_n22(_uploadFile, _downloadFile, value.state),
        questionId: value.questionId,
        category: value.category
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kickedPlayers: Array<string>;
    activePlayers: bigint;
    playerReferrals: Array<_PlayerReferral>;
    blockedPlayers: Array<string>;
    suspiciousUsers: Array<string>;
    roomCode: string;
    roundLog: Array<_RoundLogEntry>;
}): {
    kickedPlayers: Array<string>;
    activePlayers: bigint;
    playerReferrals: Array<PlayerReferral>;
    blockedPlayers: Array<string>;
    suspiciousUsers: Array<string>;
    roomCode: string;
    roundLog: Array<RoundLogEntry>;
} {
    return {
        kickedPlayers: value.kickedPlayers,
        activePlayers: value.activePlayers,
        playerReferrals: value.playerReferrals,
        blockedPlayers: value.blockedPlayers,
        suspiciousUsers: value.suspiciousUsers,
        roomCode: value.roomCode,
        roundLog: from_candid_vec_n6(_uploadFile, _downloadFile, value.roundLog)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: string;
    winner: [] | [string];
    totalSubmissions: bigint;
    timeTaken: [] | [bigint];
    roundNumber: bigint;
}): {
    question: string;
    winner?: string;
    totalSubmissions: bigint;
    timeTaken?: bigint;
    roundNumber: bigint;
} {
    return {
        question: value.question,
        winner: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.winner)),
        totalSubmissions: value.totalSubmissions,
        timeTaken: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.timeTaken)),
        roundNumber: value.roundNumber
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    live: null;
} | {
    finished: null;
} | {
    waiting: null;
}): QuizStatus {
    return "live" in value ? QuizStatus.live : "finished" in value ? QuizStatus.finished : "waiting" in value ? QuizStatus.waiting : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    strict: null;
} | {
    smart: null;
}): AnswerMode {
    return "strict" in value ? AnswerMode.strict : "smart" in value ? AnswerMode.smart : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: {
        cooldownActive: null;
    };
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: Variant_cooldownActive;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    almost: null;
} | {
    correct: null;
} | {
    wrong: null;
}): AnswerStatus {
    return "almost" in value ? AnswerStatus.almost : "correct" in value ? AnswerStatus.correct : "wrong" in value ? AnswerStatus.wrong : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "paid" in value ? WithdrawalStatus.paid : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _JoinError;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: JoinError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_JoinError_n30(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cooldownActive: null;
}): Variant_cooldownActive {
    return "cooldownActive" in value ? Variant_cooldownActive.cooldownActive : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nameTaken: null;
} | {
    playerKicked: null;
} | {
    invalidName: null;
} | {
    playerBlocked: null;
} | {
    wrongRoomCode: null;
}): JoinError {
    return "nameTaken" in value ? JoinError.nameTaken : "playerKicked" in value ? JoinError.playerKicked : "invalidName" in value ? JoinError.invalidName : "playerBlocked" in value ? JoinError.playerBlocked : "wrongRoomCode" in value ? JoinError.wrongRoomCode : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _WithdrawalError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: WithdrawalError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_WithdrawalError_n33(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insufficientBalance: null;
} | {
    invalidUpiId: null;
} | {
    pendingRequestExists: null;
} | {
    cooldownActive: null;
}): WithdrawalError {
    return "insufficientBalance" in value ? WithdrawalError.insufficientBalance : "invalidUpiId" in value ? WithdrawalError.invalidUpiId : "pendingRequestExists" in value ? WithdrawalError.pendingRequestExists : "cooldownActive" in value ? WithdrawalError.cooldownActive : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizStatePublic;
}): {
    __kind__: "ok";
    ok: QuizStatePublic;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_QuizStatePublic_n22(_uploadFile, _downloadFile, value.ok)
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _QuizStatePublic;
} | {
    err: _QuizError;
}): {
    __kind__: "ok";
    ok: QuizStatePublic;
} | {
    __kind__: "err";
    err: QuizError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_QuizStatePublic_n22(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_QuizError_n39(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answerNotAccepted: string;
} | {
    quizAlreadyHasWinner: null;
} | {
    quizNotLive: null;
} | {
    insufficientCoins: null;
} | {
    answerLimitExceeded: null;
}): {
    __kind__: "answerNotAccepted";
    answerNotAccepted: string;
} | {
    __kind__: "quizAlreadyHasWinner";
    quizAlreadyHasWinner: null;
} | {
    __kind__: "quizNotLive";
    quizNotLive: null;
} | {
    __kind__: "insufficientCoins";
    insufficientCoins: null;
} | {
    __kind__: "answerLimitExceeded";
    answerLimitExceeded: null;
} {
    return "answerNotAccepted" in value ? {
        __kind__: "answerNotAccepted",
        answerNotAccepted: value.answerNotAccepted
    } : "quizAlreadyHasWinner" in value ? {
        __kind__: "quizAlreadyHasWinner",
        quizAlreadyHasWinner: value.quizAlreadyHasWinner
    } : "quizNotLive" in value ? {
        __kind__: "quizNotLive",
        quizNotLive: value.quizNotLive
    } : "insufficientCoins" in value ? {
        __kind__: "insufficientCoins",
        insufficientCoins: value.insufficientCoins
    } : "answerLimitExceeded" in value ? {
        __kind__: "answerLimitExceeded",
        answerLimitExceeded: value.answerLimitExceeded
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AutoRoundResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AutoRoundResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AutoRoundResult_n42(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoundLogEntry>): Array<RoundLogEntry> {
    return value.map((x)=>from_candid_RoundLogEntry_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AnswerMode_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerMode): _AnswerMode {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnswerMode): {
    strict: null;
} | {
    smart: null;
} {
    return value == AnswerMode.strict ? {
        strict: null
    } : value == AnswerMode.smart ? {
        smart: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
